# api/api-specs/common.yaml
openapi: 3.0.3
info:
  title: Common API Definitions
  version: 0.0.0

paths: {} # This is a dummy path to resolve the 'Missing property paths' error.

components:
  # ===== Common schemas ======================================================== #
  schemas:
    ErrorResponse:
      type: object
      properties:
        statusCode:
          type: integer
          example: 400
          description: HTTP Status Code
        error:
          type: string
          example: Bad Request
          description: Type of Error
        message:
          type: string
          example: Invalid request parameters.
          description: Error message
        details:
          type: array
          description: Error details information
          items:
            $ref: '#/components/schemas/ErrorDetail'
    ErrorDetail:
      type: object
      properties:
        field:
          type: string
          description: The name of field where the error occurred
          example: title
        message:
          type: string
          description: The field error message that occurred
          example: Required field missing
  # ===== Common response ======================================================== #
  responses:
    BadRequest:
      description: 400 Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            statusCode: 400
            error: Bad Request
            message: Invalid request parameters.
            details:
              - field: unit_name
                message: Invalid unit name.
    Unauthorized:
      description: 401 Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            statusCode: 401
            error: Unauthorized
            message: Authentication credentials were not provided
    Forbidden:
      description: 403 Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            statusCode: 403
            error: Forbidden
            message: You do not have permission to access this resource.
    NotFound:
      description: 404 Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            statusCode: 404
            error: Not Found
            message: The requested resource was not found.
    Conflict:
      description: 409 Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            statusCode: 409
            error: Conflict
            message: Resource already exists.
            details:
              field: user_name
              message: This username is already in use.
    InternalServerError:
      description: 500 Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            statusCode: 500
            error: Internal Server Error
            message: Server encountered an unexpected condition.
    ServiceUnavailable:
      description: 503 Service Unavailable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            statusCode: 503
            error: Service Unavailable
            message: Service is under maintenance. Please try again later.
